name: CI Pipeline

on:
    push:
        branches:
            - master
            - 'feature/*'
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 24
              uses: actions/setup-java@v4
              with:
                  java-version: '24'
                  distribution: 'temurin'
                  cache: maven

            - name: Build with Maven
              run: mvn clean install